package com.example.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.calendar.activity.dao.ScheduleQueryBean;

import com.example.dao.ScheduleQueryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scheduleQueryBeanDaoConfig;

    private final ScheduleQueryBeanDao scheduleQueryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scheduleQueryBeanDaoConfig = daoConfigMap.get(ScheduleQueryBeanDao.class).clone();
        scheduleQueryBeanDaoConfig.initIdentityScope(type);

        scheduleQueryBeanDao = new ScheduleQueryBeanDao(scheduleQueryBeanDaoConfig, this);

        registerDao(ScheduleQueryBean.class, scheduleQueryBeanDao);
    }
    
    public void clear() {
        scheduleQueryBeanDaoConfig.clearIdentityScope();
    }

    public ScheduleQueryBeanDao getScheduleQueryBeanDao() {
        return scheduleQueryBeanDao;
    }

}
